package com.josh.java.training.javafeatures.methodreferences.instancemethod;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class Employee {

	String name;
	Integer age;
	int salary;

	// generated by IDE, getters, setters, constructor, toString
}